"""Example: simulated autogenerated bqetl DAG (daily at 04:15).

Only waits on `copy_deduplicate_all`. Demonstrates a consumer on a different
schedule from example_downstream_bqetl_a, which is why the task-markers DAG
needs to emit distinct `execution_date` templates per consumer.
"""

import datetime
from datetime import timedelta

from airflow import models
from airflow.operators.empty import EmptyOperator
from airflow.sensors.external_task import ExternalTaskSensor

SOURCE_DAG_ID = "example_copy_dedup_source"

ALLOWED_STATES = ["success"]
FAILED_STATES = ["failed", "upstream_failed", "skipped"]

default_args = {
    "owner": "example@mozilla.com",
    "start_date": datetime.datetime(2026, 4, 1),
    "retries": 0,
}

with models.DAG(
    "example_downstream_bqetl_b",
    # Runs at 04:15; source runs at 01:00 → execution_delta = 3h15m.
    schedule_interval="15 4 * * *",
    catchup=False,
    default_args=default_args,
    tags=["example", "generated"],
) as dag:
    wait_for_copy_deduplicate_all = ExternalTaskSensor(
        task_id="wait_for_copy_deduplicate_all",
        external_dag_id=SOURCE_DAG_ID,
        external_task_id="copy_deduplicate_all",
        execution_delta=timedelta(hours=3, minutes=15),
        mode="reschedule",
        allowed_states=ALLOWED_STATES,
        failed_states=FAILED_STATES,
    )

    run_query = EmptyOperator(task_id="run_query")

    wait_for_copy_deduplicate_all >> run_query
