"""Example: simulated autogenerated bqetl DAG (daily at 02:00).

Waits on both `copy_deduplicate_all` and `copy_deduplicate_main_ping`. These
sensors are what bigquery-etl already generates today. The task-markers DAG's
markers point at the task_ids declared here.
"""

import datetime
from datetime import timedelta

from airflow import models
from airflow.operators.empty import EmptyOperator
from airflow.sensors.external_task import ExternalTaskSensor

SOURCE_DAG_ID = "example_copy_dedup_source"

ALLOWED_STATES = ["success"]
FAILED_STATES = ["failed", "upstream_failed", "skipped"]

default_args = {
    "owner": "example@mozilla.com",
    "start_date": datetime.datetime(2026, 4, 1),
    "retries": 0,
}

with models.DAG(
    "example_downstream_bqetl_a",
    # Runs at 02:00; source runs at 01:00 → execution_delta = 1h.
    schedule_interval="0 2 * * *",
    catchup=False,
    default_args=default_args,
    tags=["example", "generated"],
) as dag:
    wait_for_copy_deduplicate_all = ExternalTaskSensor(
        task_id="wait_for_copy_deduplicate_all",
        external_dag_id=SOURCE_DAG_ID,
        external_task_id="copy_deduplicate_all",
        execution_delta=timedelta(hours=1),
        mode="reschedule",
        allowed_states=ALLOWED_STATES,
        failed_states=FAILED_STATES,
    )

    wait_for_copy_deduplicate_main_ping = ExternalTaskSensor(
        task_id="wait_for_copy_deduplicate_main_ping",
        external_dag_id=SOURCE_DAG_ID,
        external_task_id="copy_deduplicate_main_ping",
        execution_delta=timedelta(hours=1),
        mode="reschedule",
        allowed_states=ALLOWED_STATES,
        failed_states=FAILED_STATES,
    )

    run_query = EmptyOperator(task_id="run_query")

    [wait_for_copy_deduplicate_all, wait_for_copy_deduplicate_main_ping] >> run_query
