region: us-west-2
airflow_bucket: telemetry-test-bucket
spark_bucket: telemetry-spark-emr-2

emr_key_name: mozilla_vitillo
emr_release_label: emr-4.3.0
emr_flow_role: telemetry-spark-cloudformation-TelemetrySparkInstanceProfile-1SATUBVEXG7E3
emr_service_role: EMR_DefaultRole
emr_instance_type: c3.4xlarge

db_uri: mysql
db_user: airflow
db_password: airflow

airflow_enable_auth: false
