region: us-west-2
spark_bucket: telemetry-spark-emr-2
airflow_bucket: telemetry-airflow
public_output_bucket: telemetry-public-analysis-2
private_output_bucket: telemetry-parquet

emr_key_name: mozilla_vitillo
emr_flow_role: telemetry-spark-cloudformation-TelemetrySparkInstanceProfile-1SATUBVEXG7E3
emr_service_role: EMR_DefaultRole
emr_instance_type: c3.4xlarge

ecs_sg_name: telemetry-ecs
ecs_key_name: mozilla_vitillo
ecs_vpc_id: vpc-4283d227
ecs_vpc_subnet_id: subnet-125a7c77
ecs_cluster_name: telemetry
ecs_instance_type: c4.2xlarge
ecs_role: arn:aws:iam::927034868273:role/telemetry-ecs-cloudformation-TelemetryECSRole-1UAYK6XNB6DG0
ecs_asg_lc_name: telemetry-ecs-lc
ecs_asg_asg_name: telemetry-ecs-asg

elb_name: telemetry-ecs
elb_sg_name: telemetry-workflow-elb
ssl_cert_id: arn:aws:iam::927034868273:server-certificate/cloudfront/exp20180829_cf_star_telemetry_mozilla_org

db_uri: telemetry-ecs-airflow.cppmil15uwvg.us-west-2.rds.amazonaws.com
db_user: airflow
db_password: telemetry-airflow  # DB is not accessible from the outside world

metadata_bucket: net-mozaws-prod-us-west-2-pipeline-metadata
